[LOCAL]

enable.hive = false
hive.database = null

account.filter = active_ind = 1
party.filter =
address.filter =

kafka.topic = sbdl_kafka_local
kafka.bootstrap.servers = localhost:9092
kafka.security.protocol = PLAINTEXT
kafka.sasl.mechanism =
kafka.client.dns.lookup =
kafka.sasl.jaas.config =
kafka.api_key =
kafka.api_secret =


[QA]

enable.hive = true
hive.database = sbdl_qa

account.filter = active_ind = 1
party.filter =
address.filter =

kafka.topic = sbdl_kafka_qa
kafka.bootstrap.servers = qa-kafka1:9092,qa-kafka2:9092
kafka.security.protocol = SASL_SSL
kafka.sasl.mechanism = PLAIN
kafka.client.dns.lookup = use_all_dns_ips
kafka.sasl.jaas.config =
kafka.api_key = ${KAFKA_API_KEY}
kafka.api_secret = ${KAFKA_API_SECRET}


[PROD]

enable.hive = true
hive.database = sbdl_prod

account.filter = active_ind = 1
party.filter =
address.filter =

kafka.topic = sbdl_kafka_prod
kafka.bootstrap.servers = prod-kafka1:9092,prod-kafka2:9092
kafka.security.protocol = SASL_SSL
kafka.sasl.mechanism = PLAIN
kafka.client.dns.lookup = use_all_dns_ips
kafka.sasl.jaas.config =
kafka.api_key = ${KAFKA_API_KEY}
kafka.api_secret = ${KAFKA_API_SECRET}

